# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"r\n\x05Robot\x12\x14\n\x0cjoint_angles\x18\x01 \x03(\x01\x12\x18\n\x10joint_velocities\x18\x02 \x03(\x01\x12\x10\n\x08tcp_pose\x18\x03 \x03(\x01\x12\x14\n\x0ctcp_velocity\x18\x04 \x03(\x01\x12\x11\n\ttcp_force\x18\x05 \x03(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROBOT']._serialized_start=22
  _globals['_ROBOT']._serialized_end=136
# @@protoc_insertion_point(module_scope)
